### ISSUE TITLE
Version 2.16.8 seems to have an advantage over the later versions with size limit

### ISSUE THREAD

**Issue by tinmanog** [nixxquality/WebMConverter#124]
Lately I've been noticing the webms I make cut off before the end of the trimmed section.
So let's say I trimmed 3 minutes but the converted webm is only 2 minutes and 30 seconds
I thought it might be the files so I decided to test it out on a file that I had no problems making a webm of that was especially long. We're talking 5 minutes and 30 seconds here. Sure enough it cut off at 4 minutes. I run into this with just about any length of time 2 minutes or longer that always cuts short. I realized it must have been because I downloaded the latest version and took 2.16.8 out of the trash bin to test it out.
Didn't have this problem with 2.16.8 though. The size limit I placed for the current version and 2.16.8 was 8 mb. It cuts off early for the latest one but with 2.16.8 it always manages to convert the entirety of the video but ends up as 7.6 mb. A lot of the lengthy webms I make with 2.16.8 usually end up with that magical number 7.6 mb 

I got around the latest version's hiccups by manually putting in the bitrate but it'd be easier for it to do it right automatically.

Could it have something to do with this?
https://github.com/nixxquality/WebMConverter/issues/120

**Comment by nixxquality** [comment]
I'll chalk it up to ffmpeg's filesize limit function being pretty broken.

Try manually specifying a bitrate that is a tad lower than the automatically generated one.

**Comment by tinmanog** [comment]
Isn't the ffmpeg the same between 2.16.8 and the later versions?

**Comment by nixxquality** [comment]
It is, but since 2.16.8 I'm expanding the MiB to bytes manually because that is one part of the filesize limit that is broken in ffmpeg.

The only "solution" to this issue would be to reduce the automatically generated bitrate by ~5% every time, but that wouldn't be enough in every case, and it wouldn't be necessary in others.

Only other thing I can think of adding is a warning that tells you your entire video didn't fit in the filesize limit, but that's still something that would have to notify the user after the fact.

**Comment by tinmanog** [comment]
Eh whatever I'll just use 2.16.8 then

**Comment by nixxquality** [comment]
On second thought, I'll go through with the "reduce automatically generated bitrate by x%" change.
Seems to be the only way to deal with VP8 being shit.
